version: "1"  # optional since v1.27.0
services:
  server:
    ports:
      - "3000:3000"
    build: .
    links:
      - db
  db:
    ports:
      - "3306:3306"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
